services:
  bcv-scraper:
    build: .
    container_name: bcv-scraper
    ports:
      - "8100:8100"
    environment:
      - TZ=America/Caracas
      - BCV_VERIFY_SSL=false
      - DB_HOST=postgres_central
      - DB_PORT=5432
      - DB_NAME=bcv_scraper
      - DB_USER=admin_root
      - DB_PASSWORD=cattivellio_master
      - SCRAPE_API_KEY=bbClrnUU5qvvo9CUqUVoIBmTx15ETkV-z6r93TRsSVw
    restart: unless-stopped

networks:
  default:
    name: postgree_red_central_db
    external: true
