services:
  bcv-scraper:
    build: .
    container_name: bcv-scraper
    ports:
      - "8100:8100"
    volumes:
      - /home/cattivellio/docker_data/bcv-scraper/data:/app/data
    environment:
      - TZ=America/Caracas
      - BCV_VERIFY_SSL=false
    restart: unless-stopped
